# **ETL**

---

### Extracción de datos

In [46]:
# Librerias a utilizar
import requests
import pandas as pd
import calendar
import io
import datetime
import json

In [297]:
# Extraemos los datos mediante una API 

# Creamos lista donde almacenaremos todos los datos
all_data = []

# Iteramos para extraer los datos de los años de interes, en este caso de 1950 a 2023
for i in range(1970, 2023):
    year = i
    for mes in range (1, 13):
        # Tomamos el último dia de cada mes
        last_day = calendar.monthrange(year, mes)[1]
        starttime = f"{year}-{mes}-01"
        endtime = f"{year}-{mes}-{last_day}"
        # El url de la api con los parámetros, donde filtramos buscando magnitudes mayores a 4
        url = f"https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime={starttime}&endtime={endtime}&minmagnitude=4"
        # Envía la solicitud HTTP a la API de USGS y procesa los datos de respuesta
        response = requests.get(url)
        data = json.loads(response.text)
        data = data["features"]
                # Itera sobre cada objeto "Feature" en la lista "data"
        for feature in data:
                # Accede a la parte "properties" de cada objeto
            properties = feature['properties']
            properties['year'] = year
            properties['month'] = mes

            all_data.append(properties)
    # Crea un dataframe de Pandas a partir de la lista de eventos sísmicos
    
            

# Realizamos la misma extracción, pero para el año 2023 de forma actualizada siempre al tiempo actual
# Tomamos el mes actual
mes_actual = datetime.datetime.now().month
# Iteramos por mes, con tope en el mes actual
for mes in range (1, mes_actual +1):
    # Tomamos el último dia de cada mes
    last_day = calendar.monthrange(2023, mes)[1]
    starttime = f"2023-{mes}-01"
    endtime = f"2023-{mes}-{last_day}"
    url = f"https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime={starttime}&endtime={endtime}&minmagnitude=4"
    response = requests.get(url)
    data = json.loads(response.text)
    data = data["features"]
    # Itera sobre cada objeto "Feature" en la lista "data"
    for feature in data:
     # Accede a la parte "properties" de cada objeto
        properties = feature['properties']
        properties['year'] = 2023
        properties['month'] = mes
    # Crea un dataframe de Pandas a partir de la lista de eventos sísmicos
        all_data.append(properties)
            
# Concatenamos todos los dataframes en uno solo
df_total = pd.DataFrame(all_data)

In [313]:
# Observamos
df_total

,mag,place,tz,felt,cdi,mmi,alert,status,tsunami,sig,...,code,types,nst,dmin,rms,gap,magType,type,year,month
0,4.09,"65km ENE of Beatty, NV",NaN,NaN,NaN,NaN,None,reviewed,0,257,...,3324919,",origin,phase-data,",13.0,1.749,0.31,253.0,ml,nuclear explosion,1970,1
1,5.90,"59 km NNE of Port-Olry, Vanuatu",NaN,NaN,NaN,3.894,None,reviewed,0,536,...,800507,",origin,shakemap,",NaN,NaN,NaN,NaN,mw,earthquake,1970,1
2,6.14,Fiji region,NaN,NaN,NaN,NaN,None,reviewed,0,580,...,800471,",origin,",NaN,NaN,NaN,NaN,mw,earthquake,1970,1
3,5.27,"195 km WSW of Linxia Chengguanzhen, China",NaN,NaN,NaN,NaN,None,reviewed,0,427,...,800431,",origin,",NaN,NaN,NaN,NaN,mw,earthquake,1970,1
4,5.77,"38 km SSE of San Cristóbal, Venezuela",NaN,NaN,NaN,6.276,None,reviewed,0,512,...,800429,",origin,shakemap,",NaN,NaN,NaN,NaN,mw,earthquake,1970,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461654,5.30,"82 km ESE of Katsuren-haebaru, Japan",NaN,2.0,2.7,NaN,None,reviewed,0,433,...,7000jxaa,",dyfi,internal-moment-tensor,moment-tensor,ori...",74.0,0.909,0.83,64.0,mww,earthquake,2023,5
461655,5.10,"Ryukyu Islands, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jxab,",origin,phase-data,",77.0,0.888,1.17,64.0,mb,earthquake,2023,5
461656,4.30,"45 km NNE of Klyuchi, Russia",NaN,NaN,NaN,NaN,None,reviewed,0,284,...,7000jxa6,",origin,phase-data,",40.0,3.949,0.63,126.0,mb,earthquake,2023,5
461657,5.10,None,NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jx9j,",origin,phase-data,",66.0,0.682,0.59,121.0,mww,earthquake,2023,5
461658,4.20,"66 km NNE of Bandar Abbas, Iran",NaN,NaN,NaN,NaN,None,reviewed,0,271,...,7000jx9i,",origin,phase-data,",48.0,2.770,0.75,143.0,mb,earthquake,2023,5

In [299]:
# Observamos las columnas, hay algunas que no aportan nada de información útil para el análisis
df_total.columns

Index(['mag', 'place', 'time', 'updated', 'tz', 'url', 'detail', 'felt', 'cdi',
       'mmi', 'alert', 'status', 'tsunami', 'sig', 'net', 'code', 'ids',
       'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'magType', 'type',
       'title', 'year', 'month'],
      dtype='object')

In [300]:
# Eliminamos las columnas que no utilizaremos
df_total.drop(['time', 'updated',"url","detail","ids","sources","title"],inplace=True,axis=1)

In [312]:
# Observamos
df_total.tail()

,mag,place,tz,felt,cdi,mmi,alert,status,tsunami,sig,...,code,types,nst,dmin,rms,gap,magType,type,year,month
461654,5.3,"82 km ESE of Katsuren-haebaru, Japan",NaN,2.0,2.7,NaN,None,reviewed,0,433,...,7000jxaa,",dyfi,internal-moment-tensor,moment-tensor,ori...",74.0,0.909,0.83,64.0,mww,earthquake,2023,5
461655,5.1,"Ryukyu Islands, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jxab,",origin,phase-data,",77.0,0.888,1.17,64.0,mb,earthquake,2023,5
461656,4.3,"45 km NNE of Klyuchi, Russia",NaN,NaN,NaN,NaN,None,reviewed,0,284,...,7000jxa6,",origin,phase-data,",40.0,3.949,0.63,126.0,mb,earthquake,2023,5
461657,5.1,None,NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jx9j,",origin,phase-data,",66.0,0.682,0.59,121.0,mww,earthquake,2023,5
461658,4.2,"66 km NNE of Bandar Abbas, Iran",NaN,NaN,NaN,NaN,None,reviewed,0,271,...,7000jx9i,",origin,phase-data,",48.0,2.770,0.75,143.0,mb,earthquake,2023,5

In [337]:
# Exportamos
df_total.to_json("df_total.json")

---

# USA

In [303]:
estados2 = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
       'Hawai', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
       'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming']

In [315]:
df_total["place"].isna().sum()

0

In [314]:
df_total["place"].fillna("sin dato",inplace=True)

In [316]:
all_dfs2 = []
for i in estados2 : 
    all_dfs2.append(df_total[df_total["place"].str.contains(i)])

df_usa = pd.concat(all_dfs2, ignore_index=True)

In [317]:
df_usa

,mag,place,tz,felt,cdi,mmi,alert,status,tsunami,sig,...,code,types,nst,dmin,rms,gap,magType,type,year,month
0,4.5,"3 km NNW of Fayette, Alabama",NaN,NaN,NaN,5.447,None,reviewed,0,312,...,p0000brg,",origin,shakemap,trump-shakemap,",NaN,NaN,NaN,NaN,mb,earthquake,1975,6
1,4.2,"4 km SW of Brookwood, Alabama",NaN,NaN,NaN,NaN,None,reviewed,0,271,...,p0002tkj,",impact-text,origin,phase-data,",NaN,NaN,0.80,NaN,mb,rock burst,1986,5
2,4.8,"15 km NNW of Flomaton, Alabama",NaN,NaN,NaN,6.012,None,reviewed,0,354,...,p00089hq,",impact-text,origin,phase-data,shakemap,trump-...",NaN,NaN,0.98,NaN,mb,earthquake,1997,10
3,4.8,"14 km WNW of North Johns, Alabama",NaN,NaN,NaN,NaN,None,reviewed,0,354,...,p000918y,",impact-text,origin,phase-data,",NaN,NaN,1.00,NaN,mb,rock burst,1999,1
4,4.6,"8 km S of Valley Head, Alabama",NaN,17204.0,6.0,4.987,green,reviewed,0,926,...,605341,",associate,dyfi,focal-mechanism,impact-text,lo...",21.0,NaN,0.07,154.0,mw,earthquake,2003,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22676,4.0,"23 km SE of Kelly, Wyoming",NaN,153.0,3.4,4.370,green,reviewed,0,298,...,10004t1f,",cap,dyfi,impact-text,losspager,moment-tensor,...",NaN,0.195,1.16,18.0,mwr,earthquake,2016,2
22677,4.8,"4 km ENE of Bondurant, Wyoming",NaN,578.0,3.9,4.640,green,reviewed,0,580,...,20006umx,",cap,dyfi,impact-text,losspager,moment-tensor,...",NaN,0.373,1.14,7.0,mwr,earthquake,2016,8
22678,4.0,"57 km S of Ten Sleep, Wyoming",NaN,58.0,4.1,3.130,green,reviewed,0,270,...,2000bi6d,",dyfi,losspager,moment-tensor,origin,phase-dat...",NaN,1.074,0.74,63.0,mwr,earthquake,2017,11
22679,4.0,"26 km ESE of Wright, Wyoming",NaN,NaN,NaN,NaN,None,reviewed,0,246,...,6000exg9,",origin,phase-data,",NaN,0.984,0.42,54.0,mb,mining explosion,2021,7
22680,4.1,"11 km E of Wright, Wyoming",NaN,NaN,NaN,NaN,None,reviewed,0,259,...,6000jis8,",origin,phase-data,",24.0,1.021,0.89,69.0,mb,mining explosion,2023,1

In [318]:
df_usa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22681 entries, 0 to 22680
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   mag      22681 non-null  float64
 1   place    22681 non-null  object
 2   tz       1 non-null      float64
 3   felt     2714 non-null   float64
 4   cdi      2714 non-null   float64
 5   mmi      2733 non-null   float64
 6   alert    1422 non-null   object
 7   status   22681 non-null  object
 8   tsunami  22681 non-null  int64
 9   sig      22681 non-null  int64
 10  net      22681 non-null  object
 11  code     22681 non-null  object
 12  types    22681 non-null  object
 13  nst      7120 non-null   float64
 14  dmin     5886 non-null   float64
 15  rms      18610 non-null  float64
 16  gap      10151 non-null  float64
 17  magType  22679 non-null  object
 18  type     22681 non-null  object
 19  year     22681 non-null  int64
 20  month    22681 non-null  int64
dtypes: float64(9), int64(4), object(8)
memory usage: 3.6+ MB

In [336]:
df_usa["place"] = df_usa["place"].str.strip()
df_usa[["place1","place2","place3"]] = df_usa["place"].str.split(",",expand=True)
df_usa

,mag,place,tz,felt,cdi,mmi,alert,status,tsunami,sig,...,dmin,rms,gap,magType,type,year,month,place1,place2,place3
0,4.5,"3 km NNW of Fayette, Alabama",NaN,NaN,NaN,5.447,None,reviewed,0,312,...,NaN,NaN,NaN,mb,earthquake,1975,6,3 km NNW of Fayette,Alabama,None
1,4.2,"4 km SW of Brookwood, Alabama",NaN,NaN,NaN,NaN,None,reviewed,0,271,...,NaN,0.80,NaN,mb,rock burst,1986,5,4 km SW of Brookwood,Alabama,None
2,4.8,"15 km NNW of Flomaton, Alabama",NaN,NaN,NaN,6.012,None,reviewed,0,354,...,NaN,0.98,NaN,mb,earthquake,1997,10,15 km NNW of Flomaton,Alabama,None
3,4.8,"14 km WNW of North Johns, Alabama",NaN,NaN,NaN,NaN,None,reviewed,0,354,...,NaN,1.00,NaN,mb,rock burst,1999,1,14 km WNW of North Johns,Alabama,None
4,4.6,"8 km S of Valley Head, Alabama",NaN,17204.0,6.0,4.987,green,reviewed,0,926,...,NaN,0.07,154.0,mw,earthquake,2003,4,8 km S of Valley Head,Alabama,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22676,4.0,"23 km SE of Kelly, Wyoming",NaN,153.0,3.4,4.370,green,reviewed,0,298,...,0.195,1.16,18.0,mwr,earthquake,2016,2,23 km SE of Kelly,Wyoming,None
22677,4.8,"4 km ENE of Bondurant, Wyoming",NaN,578.0,3.9,4.640,green,reviewed,0,580,...,0.373,1.14,7.0,mwr,earthquake,2016,8,4 km ENE of Bondurant,Wyoming,None
22678,4.0,"57 km S of Ten Sleep, Wyoming",NaN,58.0,4.1,3.130,green,reviewed,0,270,...,1.074,0.74,63.0,mwr,earthquake,2017,11,57 km S of Ten Sleep,Wyoming,None
22679,4.0,"26 km ESE of Wright, Wyoming",NaN,NaN,NaN,NaN,None,reviewed,0,246,...,0.984,0.42,54.0,mb,mining explosion,2021,7,26 km ESE of Wright,Wyoming,None
22680,4.1,"11 km E of Wright, Wyoming",NaN,NaN,NaN,NaN,None,reviewed,0,259,...,1.021,0.89,69.0,mb,mining explosion,2023,1,11 km E of Wright,Wyoming,None

In [338]:
# Exportamos
df_usa.to_json("Usa.json")

---

# Japón

In [334]:
df_japon = df_total[df_total["place"].str.contains("Japan")]
df_japon

,mag,place,tz,felt,cdi,mmi,alert,status,tsunami,sig,...,code,types,nst,dmin,rms,gap,magType,type,year,month
12,6.40,"45 km SSW of Obihiro, Japan",NaN,NaN,NaN,6.419,None,reviewed,0,630,...,800254,",origin,shakemap,trump-shakemap,",NaN,NaN,NaN,NaN,mw,earthquake,1970,1
77,5.53,"Volcano Islands, Japan region",NaN,NaN,NaN,NaN,None,reviewed,0,470,...,799066,",origin,",NaN,NaN,NaN,NaN,mw,earthquake,1970,2
107,5.54,"67 km NE of Naze, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,472,...,798599,",origin,",NaN,NaN,NaN,NaN,mw,earthquake,1970,3
127,5.70,"101 km WSW of Kurio, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,500,...,798320,",origin,",NaN,NaN,NaN,NaN,mw,earthquake,1970,3
129,5.70,"4 km WSW of Takanosu, Japan",NaN,NaN,NaN,3.951,None,reviewed,0,500,...,798303,",origin,shakemap,",NaN,NaN,NaN,NaN,mw,earthquake,1970,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461650,5.10,"75 km ESE of Katsuren-haebaru, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jxal,",origin,phase-data,",58.0,0.883,0.99,79.0,mww,earthquake,2023,5
461651,5.00,"81 km SE of Taira, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,385,...,7000jxaj,",origin,phase-data,",44.0,0.845,0.95,78.0,mb,earthquake,2023,5
461652,5.90,"79 km ESE of Katsuren-haebaru, Japan",NaN,10.0,3.1,3.841,green,reviewed,0,539,...,7000jxag,",dyfi,internal-moment-tensor,internal-origin,l...",76.0,0.871,0.75,57.0,mww,earthquake,2023,5
461654,5.30,"82 km ESE of Katsuren-haebaru, Japan",NaN,2.0,2.7,NaN,None,reviewed,0,433,...,7000jxaa,",dyfi,internal-moment-tensor,moment-tensor,ori...",74.0,0.909,0.83,64.0,mww,earthquake,2023,5
461655,5.10,"Ryukyu Islands, Japan",NaN,NaN,NaN,NaN,None,reviewed,0,400,...,7000jxab,",origin,phase-data,",77.0,0.888,1.17,64.0,mb,earthquake,2023,5

In [339]:
df_japon.to_json("Japón.json")

---

# México

In [329]:
# Dataset con magnitudes mayores a 4.0 y de 1970 a 2023
df_mex = pd.read_json("Datasets/sismos_méxico.json")
# Obervamos
df_mex

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,1970-02-03,23:08:50,6.6,15.524,-99.493,21.0,"141 km al SUR de SAN MARCOS, GRO",1970-02-04,05:08:50,revisado
1,1970-04-29,08:01:34,7.3,14.463,-92.683,44.0,"62 km al SUROESTE de CD HIDALGO, CHIS",1970-04-29,14:01:34,revisado
2,1970-04-30,02:32:58,6.5,14.608,-93.260,22.0,"100 km al SUROESTE de MAPASTEPEC, CHIS",1970-04-30,08:32:58,revisado
3,1971-09-30,02:18:00,6.5,26.880,-110.800,14.0,"92 km al SUROESTE de PUEBLO YAQUI, SON",1971-09-30,08:18:00,revisado
4,1972-10-20,02:17:46,6.6,18.700,-106.756,10.0,"238 km al OESTE de CIHUATLAN, JAL",1972-10-20,08:17:46,revisado
...,...,...,...,...,...,...,...,...,...,...
42665,2023-05-03,21:17:37,4.0,19.350,-103.870,31.0,"17 km al NOROESTE de VILLA DE ALVAREZ, COL",2023-05-04,03:17:37,verificado
42666,2023-05-03,21:39:31,4.2,16.910,-95.040,106.0,"4 km al NORTE de MATIAS ROMERO, OAX",2023-05-04,03:39:31,verificado
42667,2023-05-04,03:19:06,4.0,15.430,-92.020,212.4,"26 km al NORESTE de MOTOZINTLA, CHIS",2023-05-04,09:19:06,verificado
42668,2023-05-04,04:42:31,4.1,14.880,-94.420,16.1,"151 km al SUROESTE de TONALA, CHIS",2023-05-04,10:42:31,verificado
42669,2023-05-04,11:39:23,4.2,16.150,-94.260,82.6,"39 km al OESTE de ARRIAGA , CHIS",2023-05-04,17:39:23,verificado

In [330]:
# Separamos "referencia de localizacion"
df_mex[["Distancia","Estado"]] = df_mex["Referencia de localizacion"].str.split(",",expand=True)
df_mex.sample(3)

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus,Distancia,Estado
36479,2020-11-05,23:41:27,4.1,17.3467,-100.691,7.6,"15 km al NOROESTE de TECPAN, GRO",2020-11-06,05:41:27,revisado,15 km al NOROESTE de TECPAN,GRO
37654,2021-04-11,11:20:07,4.9,18.3810,-103.207,52.3,"44 km al SUR de COALCOMAN, MICH",2021-04-11,16:20:07,revisado,44 km al SUR de COALCOMAN,MICH
23149,2017-02-10,21:29:40,4.3,18.4107,-102.591,56.2,"50 km al NOROESTE de LA MIRA, MICH",2017-02-11,03:29:40,revisado,50 km al NOROESTE de LA MIRA,MICH

In [340]:
# Exportamos a formato json
df_mex.to_json("México.json")

---

# Requerimientos de Data Analysts

---

+ ### KPI 1

In [ ]:
# usar los datasets de la carpeta KPI1

---

+ ### KPI 2

In [ ]:
# si es posible hacer + web scrapping + de wikipedia para conseguir la data, si no CSV (USA  y Japon)

# USA : https://en.wikipedia.org/wiki/List_of_earthquakes_in_the_United_States

# Ponjas : https://en.wikipedia.org/wiki/List_of_earthquakes_in_Japan

# Mexico : https://www.worlddata.info/america/mexico/earthquakes.php

In [ ]:
# podria iterar, ya que todos utilizan el mismo código ( EL RETO SERIA EN UN SOLO BLOQUE DE CÓDIGO SACAR LOS 3)

In [12]:
# Mexico
import pandas as pd
from bs4 import BeautifulSoup

url = 'https://www.worlddata.info/america/mexico/earthquakes.php'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

seccion = soup.find('table', {'class': 'std100 hover'})
rows = seccion.find_all("tr")

data = []
for row in rows[1:]: # Saltamos la primera fila que contiene los encabezados de la tabla
    cols = row.find_all('td')
    date_time = cols[0].text.strip()
    location = cols[1].text.strip()
    magnitude = cols[2].text.strip()
    intensity = cols[3].text.strip()
    emission_date_time = cols[4].text.strip()
    data.append([date_time, location, magnitude, intensity, emission_date_time])

# Crear dataframe
df = pd.DataFrame(data, columns=["date_time", "location", "magnitude", "intensity", "emission_date_time"])
# Mostrar el dataframe
df

,date_time,location,magnitude,intensity,emission_date_time
0,09/22/2022,"Mexico City, Michoacan",24 km,6.8,3
1,09/19/2022,"Michoacan, Colima, Jalisco",15 km,7.6,2
2,05/25/2022,Oaxaca,34 km,5.5,0
3,09/08/2021,Guerrero,20 km,7.0,3
4,06/23/2020,Oaxaca,26 km,7.4,10
...,...,...,...,...,...
61,01/08/1956,Guerrero,26 km,6.5,0
62,02/05/1954,Chiapas,,6.2,6
63,07/09/1951,Oaxaca (Miahiatlan),,6.2,1
64,12/14/1950,Acapulco,49 km,7.5,0
65,11/17/1950,Guerrero,,6.8,0

In [4]:
# México
import requests
from bs4 import BeautifulSoup

url = 'https://www.worlddata.info/america/mexico/earthquakes.php'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

seccion = soup.find('table', {'class': 'std100 hover'})
rows = seccion.find_all("tr")
print(rows)
for row in rows[1:]: # Saltamos la primera fila que contiene los encabezados de la tabla
    cols = row.find_all('td')
    date_time = cols[0].text.strip()
    location = cols[1].text.strip()
    magnitude = cols[2].text.strip()
    intensity = cols[3].text.strip()
    emission_date_time = cols[4].text.strip()
    print(date_time, location, magnitude, intensity, emission_date_time)

[<tr class="no-sort"><th>Date</th><th>Region</th><th>Depth</th><th>Magnitude</th><th>Deaths</th><th>Total damage</th></tr>, <tr><td data-sort="20220922">09/22/2022</td><td>Mexico City, Michoacan</td><td>24 km</td><td>6.8</td><td>3</td><td data-sort="9.0"><div class="hrzScale" style="width:21%;"></div></td></tr>, <tr><td data-sort="20220919">09/19/2022</td><td>Michoacan, Colima, Jalisco</td><td>15 km</td><td>7.6</td><td>2</td><td data-sort="13.0"><div class="hrzScale" style="width:30%;"></div></td></tr>, <tr><td data-sort="20220525">05/25/2022</td><td>Oaxaca</td><td>34 km</td><td>5.5</td><td>0</td><td data-sort="0.0"><div class="hrzScale" style="width:0%;"></div></td></tr>, <tr><td data-sort="20210908">09/08/2021</td><td>Guerrero</td><td>20 km</td><td>7.0</td><td>3</td><td data-sort="17.0"><div class="hrzScale" style="width:40%;"></div></td></tr>, <tr><td data-sort="20200623">06/23/2020</td><td>Oaxaca</td><td>26 km</td><td>7.4</td><td>10</td><td data-sort="17.0"><div class="hrzScale" style="width:40%;"></div></td></tr>, <tr><td data-sort="20190201">02/01/2019</td><td>Chiapas; Guatemala (San Marcos)</td><td>66 km</td><td>6.7</td><td>0</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="20180216">02/16/2018</td><td>Oaxaca</td><td>22 km</td><td>7.2</td><td>14</td><td data-sort="12.0"><div class="hrzScale" style="width:28%;"></div></td></tr>, <tr><td data-sort="20170923">09/23/2017</td><td>Oaxaca</td><td>48 km</td><td>6.1</td><td>5</td><td data-sort="9.0"><div class="hrzScale" style="width:21%;"></div></td></tr>, <tr><td data-sort="20170919">09/19/2017</td><td>Mexico City, Morelos, Puebla</td><td>7 km</td><td>7.1</td><td>369</td><td data-sort="34.0"><div class="hrzScale" style="width:79%;"></div></td></tr>, <tr><td data-sort="20170908">09/08/2017</td><td>Oaxaca, Chiapas, Tabasco; Guatemala</td><td>2 km</td><td>8.2</td><td>98</td><td data-sort="31.0"><div class="hrzScale" style="width:72%;"></div></td></tr>, <tr><td data-sort="20151217">12/17/2015</td><td>Cocotitlan</td><td>5 km</td><td>6.6</td><td>2</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="20140729">07/29/2014</td><td>Oaxaca</td><td>7 km</td><td>6.3</td><td>1</td><td data-sort="11.0"><div class="hrzScale" style="width:26%;"></div></td></tr>, <tr><td data-sort="20140707">07/07/2014</td><td>San Marcos</td><td>7 km</td><td>6.9</td><td>3</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="20140508">05/08/2014</td><td>Tecpan</td><td>21 km</td><td>6.4</td><td>0</td><td data-sort="3.0"><div class="hrzScale" style="width:7%;"></div></td></tr>, <tr><td data-sort="20140418">04/18/2014</td><td>Guerrero; Mexico City</td><td>32 km</td><td>7.2</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="20130821">08/21/2013</td><td>San Marcos, Acapulco</td><td>7 km</td><td>6.2</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="20120320">03/20/2012</td><td>Guerrero, Oaxaca</td><td>47 km</td><td>7.4</td><td>2</td><td data-sort="17.0"><div class="hrzScale" style="width:40%;"></div></td></tr>, <tr><td data-sort="20111211">12/11/2011</td><td>Guerrero</td><td>25 km</td><td>6.4</td><td>2</td><td data-sort="11.0"><div class="hrzScale" style="width:26%;"></div></td></tr>, <tr><td data-sort="20100630">06/30/2010</td><td>San Andres Huaxpaltepec</td><td>27 km</td><td>6.2</td><td>1</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="20100404">04/04/2010</td><td>Baja California</td><td>43 km</td><td>7.2</td><td>2</td><td data-sort="18.0"><div class="hrzScale" style="width:42%;"></div></td></tr>, <tr><td data-sort="20091230">12/30/2009</td><td>Mexicali</td><td>57 km</td><td>5.9</td><td>0</td><td data-sort="2.0"><div class="hrzScale" style="width:5%;"></div></td></tr>, <tr><td data-sort="20080209">02/09/2008</td><td>Baja California</td><td>5 km</td><td>5.1</td><td>0</td><td data-sort="2.0"><div class="hrzScale" style="width:5%;"></div></td></tr>, <tr><td data-sort="20070413">04/13/2007</td><td>Guerrero, Atoyac</td><td>23 km</td><td>6.0</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="20060910">09/10/2006</td><td>Gulf Of Mexico</td><td>8 km</td><td>5.8</td><td>0</td><td data-sort="0.0"><div class="hrzScale" style="width:0%;"></div></td></tr>, <tr><td data-sort="20040101">01/01/2004</td><td>Guerrero, Mexico City</td><td>50 km</td><td>6.1</td><td>0</td><td data-sort="2.0"><div class="hrzScale" style="width:5%;"></div></td></tr>, <tr><td data-sort="20030122">01/22/2003</td><td>Villa De Alvarez, Colima, Tecoman, Jalisco</td><td>34 km</td><td>7.5</td><td>29</td><td data-sort="25.0"><div class="hrzScale" style="width:58%;"></div></td></tr>, <tr><td data-sort="20020925">09/25/2002</td><td>Acapulco</td><td>48 km</td><td>5.3</td><td>0</td><td data-sort="5.0"><div class="hrzScale" style="width:12%;"></div></td></tr>, <tr><td data-sort="20020222">02/22/2002</td><td>Mexicali, Baja California</td><td>41 km</td><td>5.5</td><td>0</td><td data-sort="2.0"><div class="hrzScale" style="width:5%;"></div></td></tr>, <tr><td data-sort="20020130">01/30/2002</td><td>Veracruz (San Andres Tuxtla, Tuxtepec)</td><td>3 km</td><td>5.9</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="19990930">09/30/1999</td><td>Oaxaca</td><td>15 km</td><td>7.5</td><td>35</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19990621">06/21/1999</td><td>Guerrero (Coahuayutla; Michoacan: Cuitzeo)</td><td>4 km</td><td>6.3</td><td>0</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="19990615">06/15/1999</td><td>Puebla, Veracruz, Oaxaca, Morelos, Guerrero</td><td>5 km</td><td>7.0</td><td>20</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19980203">02/03/1998</td><td>Oaxaca, San Agustin, San Francisco</td><td> </td><td>6.3</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="19970111">01/11/1997</td><td>Michoacan, Arteaga</td><td>26 km</td><td>7.2</td><td>1</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="19960225">02/25/1996</td><td>Off Coast Of Guerrero</td><td>15 km</td><td>7.1</td><td>0</td><td data-sort="0.0"><div class="hrzScale" style="width:0%;"></div></td></tr>, <tr><td data-sort="19951009">10/09/1995</td><td>Jalisco, Manzanillo, San Patricio Melaque</td><td>53 km</td><td>8.0</td><td>49</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19950914">09/14/1995</td><td>Guerrero, Oaxaca, Puebla, Mexico City</td><td>31 km</td><td>7.4</td><td>3</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="19890425">04/25/1989</td><td>Mexico City, Acapulco</td><td> </td><td>6.8</td><td>3</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="19850921">09/21/1985</td><td>Sw Coast (Mexico City)</td><td>13 km</td><td>7.6</td><td>0</td><td data-sort="12.0"><div class="hrzScale" style="width:28%;"></div></td></tr>, <tr><td data-sort="19850919">09/19/1985</td><td>Michoacan (Mexico City)</td><td>47 km</td><td>8.1</td><td>9500</td><td data-sort="36.0"><div class="hrzScale" style="width:84%;"></div></td></tr>, <tr><td data-sort="19830124">01/24/1983</td><td>Oaxaca (Salina Cruz)</td><td>39 km</td><td>6.7</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="19820607">06/07/1982</td><td>Guererro, Orziba, Oaxaca, Guadalupe</td><td>40 km</td><td>7.0</td><td>9</td><td data-sort="11.0"><div class="hrzScale" style="width:26%;"></div></td></tr>, <tr><td data-sort="19820328">03/28/1982</td><td>Chiapas</td><td>52 km</td><td>3.5</td><td>10</td><td data-sort="9.0"><div class="hrzScale" style="width:21%;"></div></td></tr>, <tr><td data-sort="19811025">10/25/1981</td><td>Michoacan (Lazaro Cardenas)</td><td>15 km</td><td>7.3</td><td>9</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="19801024">10/24/1980</td><td>S, Huajapan De Leon, Oaxaca</td><td>35 km</td><td>6.4</td><td>300</td><td data-sort="25.0"><div class="hrzScale" style="width:58%;"></div></td></tr>, <tr><td data-sort="19800609">06/09/1980</td><td>Nw</td><td>18 km</td><td>6.4</td><td>1</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="19790314">03/14/1979</td><td>Guerrero</td><td>16 km</td><td>7.6</td><td>5</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19781129">11/29/1978</td><td>Oaxaca</td><td>47 km</td><td>7.7</td><td>9</td><td data-sort="11.0"><div class="hrzScale" style="width:26%;"></div></td></tr>, <tr><td data-sort="19780319">03/19/1978</td><td>Acapulco</td><td>14 km</td><td>6.6</td><td>1</td><td data-sort="9.0"><div class="hrzScale" style="width:21%;"></div></td></tr>, <tr><td data-sort="19760607">06/07/1976</td><td>Mexico City</td><td>39 km</td><td>6.4</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>, <tr><td data-sort="19730828">08/28/1973</td><td>Veracruz, Mexico City</td><td>40 km</td><td>6.2</td><td>600</td><td data-sort="18.0"><div class="hrzScale" style="width:42%;"></div></td></tr>, <tr><td data-sort="19730130">01/30/1973</td><td>S, Farias, Tecoman</td><td>12 km</td><td>7.5</td><td>56</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19680925">09/25/1968</td><td>South Chiapas</td><td> </td><td>5.7</td><td>20</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="19680802">08/02/1968</td><td>Oaxaca, Guerrero</td><td> </td><td>7.5</td><td>18</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="19650823">08/23/1965</td><td>Me\Xico City, Oaxaca</td><td>2 km</td><td>7.8</td><td>6</td><td data-sort="7.0"><div class="hrzScale" style="width:16%;"></div></td></tr>, <tr><td data-sort="19640706">07/06/1964</td><td>Guerrero</td><td> </td><td>7.4</td><td>78</td><td data-sort="14.0"><div class="hrzScale" style="width:33%;"></div></td></tr>, <tr><td data-sort="19620519">05/19/1962</td><td>S</td><td>15 km</td><td>7.2</td><td>3</td><td data-sort="13.0"><div class="hrzScale" style="width:30%;"></div></td></tr>, <tr><td data-sort="19620511">05/11/1962</td><td>S</td><td>54 km</td><td>7.0</td><td>4</td><td data-sort="15.0"><div class="hrzScale" style="width:35%;"></div></td></tr>, <tr><td data-sort="19590826">08/26/1959</td><td>Gulf Of Campeche</td><td>31 km</td><td>6.9</td><td>25</td><td data-sort="19.0"><div class="hrzScale" style="width:44%;"></div></td></tr>, <tr><td data-sort="19590524">05/24/1959</td><td>Oaxaca;</td><td> </td><td>6.8</td><td>0</td><td data-sort="6.0"><div class="hrzScale" style="width:14%;"></div></td></tr>, <tr><td data-sort="19570728">07/28/1957</td><td>Acapulco, mexico City</td><td>1 km</td><td>7.9</td><td>65</td><td data-sort="25.0"><div class="hrzScale" style="width:58%;"></div></td></tr>, <tr><td data-sort="19560108">01/08/1956</td><td>Guerrero</td><td>26 km</td><td>6.5</td><td>0</td><td data-sort="9.0"><div class="hrzScale" style="width:21%;"></div></td></tr>, <tr><td data-sort="19540205">02/05/1954</td><td>Chiapas</td><td> </td><td>6.2</td><td>6</td><td data-sort="10.0"><div class="hrzScale" style="width:23%;"></div></td></tr>, <tr><td data-sort="19510709">07/09/1951</td><td>Oaxaca (Miahiatlan)</td><td> </td><td>6.2</td><td>1</td><td data-sort="8.0"><div class="hrzScale" style="width:19%;"></div></td></tr>, <tr><td data-sort="19501214">12/14/1950</td><td>Acapulco</td><td>49 km</td><td>7.5</td><td>0</td><td data-sort="6.0"><div class="hrzScale" style="width:14%;"></div></td></tr>, <tr><td data-sort="19501117">11/17/1950</td><td>Guerrero</td><td> </td><td>6.8</td><td>0</td><td data-sort="4.0"><div class="hrzScale" style="width:9%;"></div></td></tr>]
09/22/2022 Mexico City, Michoacan 24 km 6.8 3
09/19/2022 Michoacan, Colima, Jalisco 15 km 7.6 2
05/25/2022 Oaxaca 34 km 5.5 0
09/08/2021 Guerrero 20 km 7.0 3
06/23/2020 Oaxaca 26 km 7.4 10
02/01/2019 Chiapas; Guatemala (San Marcos) 66 km 6.7 0
02/16/2018 Oaxaca 22 km 7.2 14
09/23/2017 Oaxaca 48 km 6.1 5
09/19/2017 Mexico City, Morelos, Puebla 7 km 7.1 369
09/08/2017 Oaxaca, Chiapas, Tabasco; Guatemala 2 km 8.2 98
12/17/2015 Cocotitlan 5 km 6.6 2
07/29/2014 Oaxaca 7 km 6.3 1
07/07/2014 San Marcos 7 km 6.9 3
05/08/2014 Tecpan 21 km 6.4 0
04/18/2014 Guerrero; Mexico City 32 km 7.2 0
08/21/2013 San Marcos, Acapulco 7 km 6.2 0
03/20/2012 Guerrero, Oaxaca 47 km 7.4 2
12/11/2011 Guerrero 25 km 6.4 2
06/30/2010 San Andres Huaxpaltepec 27 km 6.2 1
04/04/2010 Baja California 43 km 7.2 2
12/30/2009 Mexicali 57 km 5.9 0
02/09/2008 Baja California 5 km 5.1 0
04/13/2007 Guerrero, Atoyac 23 km 6.0 0
09/10/2006 Gulf Of Mexico 8 km 5.8 0
01/01/2004 Guerrero, Mexico City 50 km 6.1 0
01/22/2003 Villa De Alvarez, Colima, Tecoman, Jalisco 34 km 7.5 29
09/25/2002 Acapulco 48 km 5.3 0
02/22/2002 Mexicali, Baja California 41 km 5.5 0
01/30/2002 Veracruz (San Andres Tuxtla, Tuxtepec) 3 km 5.9 0
09/30/1999 Oaxaca 15 km 7.5 35
06/21/1999 Guerrero (Coahuayutla; Michoacan: Cuitzeo) 4 km 6.3 0
06/15/1999 Puebla, Veracruz, Oaxaca, Morelos, Guerrero 5 km 7.0 20
02/03/1998 Oaxaca, San Agustin, San Francisco  6.3 0
01/11/1997 Michoacan, Arteaga 26 km 7.2 1
02/25/1996 Off Coast Of Guerrero 15 km 7.1 0
10/09/1995 Jalisco, Manzanillo, San Patricio Melaque 53 km 8.0 49
09/14/1995 Guerrero, Oaxaca, Puebla, Mexico City 31 km 7.4 3
04/25/1989 Mexico City, Acapulco  6.8 3
09/21/1985 Sw Coast (Mexico City) 13 km 7.6 0
09/19/1985 Michoacan (Mexico City) 47 km 8.1 9500
01/24/1983 Oaxaca (Salina Cruz) 39 km 6.7 0
06/07/1982 Guererro, Orziba, Oaxaca, Guadalupe 40 km 7.0 9
03/28/1982 Chiapas 52 km 3.5 10
10/25/1981 Michoacan (Lazaro Cardenas) 15 km 7.3 9
10/24/1980 S, Huajapan De Leon, Oaxaca 35 km 6.4 300
06/09/1980 Nw 18 km 6.4 1
03/14/1979 Guerrero 16 km 7.6 5
11/29/1978 Oaxaca 47 km 7.7 9
03/19/1978 Acapulco 14 km 6.6 1
06/07/1976 Mexico City 39 km 6.4 0
08/28/1973 Veracruz, Mexico City 40 km 6.2 600
01/30/1973 S, Farias, Tecoman 12 km 7.5 56
09/25/1968 South Chiapas  5.7 20
08/02/1968 Oaxaca, Guerrero  7.5 18
08/23/1965 Me\Xico City, Oaxaca 2 km 7.8 6
07/06/1964 Guerrero  7.4 78
05/19/1962 S 15 km 7.2 3
05/11/1962 S 54 km 7.0 4
08/26/1959 Gulf Of Campeche 31 km 6.9 25
05/24/1959 Oaxaca;  6.8 0
07/28/1957 Acapulco, mexico City 1 km 7.9 65
01/08/1956 Guerrero 26 km 6.5 0
02/05/1954 Chiapas  6.2 6
07/09/1951 Oaxaca (Miahiatlan)  6.2 1
12/14/1950 Acapulco 49 km 7.5 0
11/17/1950 Guerrero  6.8 0

In [ ]:
# USA
import requests
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/List_of_earthquakes_in_the_United_States'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

seccion = soup.find('div', {'class': 'mw-parser-output'})
rows = seccion.find_all("tr")
for row in rows[1:]: # Saltamos la primera fila que contiene los encabezados de la tabla
    cols = row.find_all('td')
    date_time = cols[0].text.strip()
    location = cols[1].text.strip()
    magnitude = cols[2].text.strip()
    intensity = cols[3].text.strip()
    print(date_time, location, magnitude, intensity)

In [16]:
# Japon
import requests
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/List_of_earthquakes_in_Japan'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

seccion = soup.find('table', {'id': 'stripe'})
rows = seccion.find_all("tr")
for row in rows[1:]: # Saltamos la primera fila que contiene los encabezados de la tabla
    cols = row.find_all('td')
    date_time = cols[0].text.strip()
    location = cols[1].text.strip()
    magnitude = cols[2].text.strip()
    intensity = cols[3].text.strip()
    emission_date_time = cols[4].text.strip()
    print(date_time, location, magnitude, intensity, emission_date_time)

November 29, 684 (Gregorian calendar)November 26, 684 (Julian calendar) 8.4 MK (Kawasumi scale)[6] 101–1,000 684 Hakuho earthquake 白鳳南海地震
June 5, 745 (G)June 1, 745 (J) 7.9 MK  occurred at Minoh 天平地震
July 13, 869 (G)July 9, 869 (J) 8.9 MK 1,000+[9] 869 Sanriku earthquake 貞観地震
May 27, 1293 (G)May 20, 1293 (J) 7.1 Ms 23,024[11] 1293 Kamakura earthquake 鎌倉大地震
August 3, 1361 (G)July 26, 1361 (J) 8.4 Ms  1361 Shōhei earthquake 正平南海地震
September 20, 1498 (G)September 11, 1498 (J) 8.6 MK 31,000[17] 1498 Nankai earthquake 明応地震
January 18, 1586 7.9 MK  1586 Tenshō earthquake 天正大地震
February 3, 1605 7.9 MK 5,000+[21] 1605 Nankai earthquake 慶長大地震
September 27, 1611 6.9 MK 3,700+ (Official estimate) 1611 Aizu earthquake 会津地震
December 2, 1611 8.1 2,000+ 1611 Sanriku earthquake 慶長三陸地震
June 16, 1662 7.25 – 7.6 M 700–900[24] 1662 Kanbun earthquake 寛文近江・若狭地震
1667 8.5 – 9.0 M unknown 1667 Kanbun Tokachi-oki earthquake 寛文十勝沖地震 (scientific)
November 4, 1677 8.3–8.6 Mw 569 1677 Bōsō earthquake 延宝房総沖地震
December 31, 1703 8.0 ML 5,233 1703 Genroku earthquake 元禄大地震
October 28, 1707 8.6 ML 5,000+ 1707 Hōei earthquake 宝永地震
April 24, 1771 7.4 MK 13,486[30] 1771 Great Yaeyama Tsunami 八重山地震
May 21, 1792 6.4 MK 15,448[31] 1792 Unzen earthquake and tsunami 島原大変肥後迷惑
December 18, 1828 6.9 MK 1,559 (official confirmed) 1828 Sanjō earthquake 三条地震
December 7, 1833 7.5 MJMA 150 1833 Shōnai earthquake 庄内沖地震
May 8, 1847 7.3 M 8,600+ 1847 Nagano earthquake 善光寺地震
July 9, 1854 7.25 MK 995 (official confirmed) 1854 Iga–Ueno earthquake 伊賀上野地震
December 23, 1854 8.4 MK 2,000 (estimated)[32] 1854 Tōkai earthquake 安政東海地震
December 24, 1854 8.4 MK 10,000+ 1854 Nankai earthquake 安政南海地震
November 11, 1855 6.9 MK 6,641 1855 Edo earthquake 安政江戸地震
April 9, 1858 7.0 200–300 1858 Hietsu earthquake 飛越地震
March 18, 1872 7.1 MK 551 (official confirmed) 1872 Hamada earthquake 浜田地震
February 22, 1880 5.5–6.0 0 1880 Yokohama earthquake 横浜地震
July 28, 1889 6.3 20 1889 Kumamoto earthquake 熊本地震
October 28, 1891 8.0 ML 7,273 1891 Mino–Owari earthquake 濃尾地震
June 20, 1894 6.6 ML 31 1894 Tokyo earthquake 明治東京地震
October 22, 1894 7.0 ML 726 (Official confirmed) 1894 Shōnai earthquake 庄内地震
June 15, 1896 8.5 ML 22,000+[35] 1896 Sanriku earthquake 明治三陸地震
September 1, 1923 8.3 ML 142,800[38] 1923 Great Kantō earthquake 大正関東地震(関東大震災)
May 23, 1925 6.8 ML 428 1925 Kita Tajima earthquake 北但馬地震
March 7, 1927 7.6 ML 3,020 1927 Kita Tango earthquake 北丹後地震
November 26, 1930 7.3 Ms 272 1930 North Izu earthquake 1930年北伊豆地震
March 3, 1933 8.4 Mw[40] 3,000+ 1933 Sanriku earthquake 昭和三陸地震
November 3, 1936 7.2 Ms 0 1936 Miyagi earthquake 1936年宮城県沖地震
August 2, 1940 7.5 Mw 10 1940 Shakotan earthquake 1940積丹半島沖地震
September 10, 1943 7.2 ML 1,083 1943 Tottori earthquake 鳥取地震
December 7, 1944 8.1 Mw 1,223 1944 Tōnankai earthquake 昭和東南海地震
January 13, 1945 6.8 ML 1,180 + 1,126 missing 1945 Mikawa earthquake 三河地震
December 20, 1946 8.1 Mw 1,362 1946 Nankai earthquake 昭和南海地震
June 28, 1948 7.1 Mw 3,769 1948 Fukui earthquake 福井地震
March 4, 1952 8.1 Mw 28 1952 Hokkaido earthquake 1952年十勝沖地震
August 19, 1961 7.0 8 1961 Kita Mino earthquake 北美濃地震
June 16, 1964 7.6 Mw 26 1964 Niigata earthquake 新潟地震
April 1, 1968 7.5 Mw 0 1968 Hyūga-nada earthquake 1968年日向灘地震
May 16, 1968 8.2 Mw 52 1968 Tokachi earthquake 1968年十勝沖地震
June 17, 1973 7.8 Mw 0 1973 Nemuro earthquake 1973根室半島沖地震
May 9, 1974 6.5 Ms 25 1974 Izu Peninsula earthquake 1974年伊豆半島沖地震
June 12, 1978 7.7 Ms 28 1978 Miyagi earthquake 宮城県沖地震
May 26, 1983 7.8 Ms 104 1983 Sea of Japan earthquake 日本海中部地震
September 14, 1984 6.3 Ms 29 1984 Otaki earthquake 長野県西部地震
December 17, 1987 6.7 Mw 2 1987 Chiba earthquake 千葉県東方沖地震
January 15, 1993 7.6 Mw 2 1993 Kushiro–Oki earthquake 釧路沖地震
July 12, 1993 7.7 Mw 202 1993 Hokkaidō earthquake 北海道南西沖地震
December 28, 1994 7.7 Mw 3 1994 offshore Sanriku earthquake 三陸はるか沖地震
January 17, 1995 7.3 Mj 6,434 Great Hanshin earthquake 兵庫県南部地震(阪神・淡路大震災)
May 4, 1998 7.5 Mw 0 1998 Ryukyu Islands earthquake 石垣島南方沖地震
March 24, 2001 6.7 Mw 2 2001 Geiyo earthquake 2001年芸予地震
September 25, 2003 8.3 Mw 1 2003 Hokkaidō earthquake 2003年十勝沖地震
October 23, 2004 6.6 Mw 68 2004 Chūetsu earthquake 新潟県中越地震
March 20, 2005 7.0 Mw 1 2005 Fukuoka earthquake 福岡県西方沖地震
August 16, 2005 7.2 Mw 0 2005 Miyagi earthquake 宮城県沖地震
November 15, 2006 8.3 Mw 0 2006 Kuril Islands earthquake 2006年千島列島沖地震
January 13, 2007 8.1 Mw 0 2007 Kuril Islands earthquake 2007年千島列島沖地震
March 25, 2007 6.9 Mw 1 2007 Noto earthquake 能登半島地震
July 16, 2007 6.6 Mw 11 2007 Chūetsu offshore earthquake 新潟県中越沖地震
June 14, 2008 6.9 Mw 12 2008 Iwate–Miyagi Nairiku earthquake 岩手・宮城内陸地震
August 11, 2009 6.6 Mw 1 2009 Shizuoka earthquake 駿河湾地震
February 26, 2010 7.0 Mw 1 Ryūkyū Islands earthquake 沖縄本島近海地震
December 21, 2010 7.4 Mw 0 Bonin Islands earthquake 父島近海地震
March 9, 2011 7.2 Mw 0 2011 Tōhoku earthquake foreshock 東北地方太平洋沖地震(Foreshock)(東日本大震災)
March 11, 2011 05:46:23 UTC(14:46 JST) 9.1 Mw 19,759 deaths,[70] (2,553 people missing[71]) 2011 Tōhoku earthquake 東北地方太平洋沖地震(東日本大震災)
March 11, 2011 06:25:50 UTC 7.1 Mw 0 2011 Tōhoku earthquake aftershock 東北地方太平洋沖地震(Aftershock)(東日本大震災)
April 7, 2011 23:30:00 JST 7.1 Mw 4 2011 Miyagi earthquake aftershock 宮城県沖地震
April 11, 2011 17:16:13 JST 6.6 Mw 6 2011 Fukushima earthquake aftershock 福島県浜通り地震
July 10, 2011 10:57:12 JST 7.0 Mw 0 2011 Fukushima earthquake aftershock 福島県浜通り地震
January 1, 2012 14:27:54 JST 6.8 Mw 0 Izu Islands, Japan 鳥島近海地震
December 7, 2012 17:18:24 JST 7.3 Mw 3 2012 Kamaishi earthquake 三陸沖地震
October 26, 2013 02:10:19 JST 7.1 Mw 0 Off the east coast of Honshu 福島県沖地震
November 22, 2014
22:08:18 JST 6.2 Mw
6.7 MJMA  2014 Nagano earthquake 長野県地震
May 30, 2015 20:24 JST 7.8 Mw 0 2015 Ogasawara earthquake 小笠原諸島西方沖地震
April 14, 2016 21:26:39 JST 6.2 Mw 9 2016 Kumamoto earthquakes 平成28年（2016年）熊本地震
April 16, 2016 1:25 JST 7.0 Mw 41 2016 Kumamoto earthquakes 平成28年（2016年）熊本地震
November 22, 2016 05:59:49 JST 6.9 Mw 0 2016 Fukushima earthquake 福島県沖地震
June 18, 2018
07:58:35 JST 5.5 Mw 4 2018 Osaka earthquake 大阪府北部地震
September 6, 2018
03:08 JST 6.6 Mw 41 2018 Hokkaido Eastern Iburi earthquake 北海道胆振東部地震
June 19, 2019  22:22 JST 6.4 Mw 0 2019 Yamagata earthquake 山形県沖地震
February 13, 2021
23:07 JST 7.1 Mw 1 2021 Fukushima earthquake 福島県沖地震
March 20, 2021
18:09:45 JST 7.0 Mw 0 March 2021 Miyagi earthquake 宮城県沖地震
October 7, 2021
22:41 JST 5.9 MW 0 2021 Chiba earthquake 千葉県北西部地震
March 16, 2022
23:36 JST 7.3 MW 4 2022 Fukushima earthquake 福島県沖地震
May 5, 2023
14:42 JST 6.2 Mw 1 2023 Ishikawa earthquake 年石川県地震

---

+ ### KPI 3

In [ ]:
# Web scrapping de estas paginas 

# https://www.shakeout.org/glb_participants.php?year=2022&start=All ( de acá todo)

# https://www.shakeout.org/participants.php?year=2022 ( de acá solo mexico y category)

---

+ ### KPI 4

In [ ]:
# usar tambien datasets de kpi 1

---

+ ### KPI 5

In [ ]:
# Web scrapping o usar el csv pero de la página. A probar

# https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=US-JP-MX

---