# **México**

In [1]:
# Librerias a utilizar
import pandas as pd

In [3]:
# Dataset con magnitudes mayores a 4.0 y de 1950 a 2023
df_mex = pd.read_csv("Datasets/sismos_méxico.csv")
# Obervamos
df_mex.head()

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,1950-09-29,00:32:20,7.0,19.00,-107.00,60.0,"257 km al SUROESTE de PUERTO VALLARTA, JAL",1950-09-29,06:32:20,revisado
1,1950-10-21,03:42:58,6.6,17.73,-106.00,33.0,"225 km al SUROESTE de CIHUATLAN, JAL",1950-10-21,09:42:58,revisado
2,1950-10-23,10:13:20,7.2,14.30,-91.80,33.0,"56 km al SURESTE de CD HIDALGO, CHIS",1950-10-23,16:13:20,revisado
3,1950-11-17,13:28:23,6.6,17.50,-100.50,33.0,"33 km al NORTE de ATOYAC DE ALVAREZ, GRO",1950-11-17,19:28:23,revisado
4,1950-12-14,08:15:50,7.2,17.22,-98.12,33.0,"47 km al OESTE de H TLAXIACO, OAX",1950-12-14,14:15:50,revisado

In [4]:
# Agregamos el id de México que es 3
df_mex["idCountry"] = 3

In [ ]:
# Exportamos a formato json
df_mex.to_json("México.json")

# Población

In [5]:
# Ingestamos via CSV la población de México para 2020
hab_mex = pd.read_csv("Datasets/Habitantes - Mexico.csv")
# Observamos
hab_mex.head()

,Estado,Población (2020),Unnamed: 2,Unnamed: 3
0,Ciudad de México,"9,209,944",NaN,La fuente de esta información es el Instituto ...
1,Estado de México,"17,511,369",NaN,NaN
2,Jalisco,"8,348,151",NaN,NaN
3,Veracruz,"8,062,703",NaN,NaN
4,Puebla,"6,583,278",NaN,NaN

In [6]:
# Realizamos las transformaciones necesarias

# Colocamos el id de México
hab_mex["idCountry"] = 3

# Dropeamos las columnas vacías
hab_mex.drop(["Unnamed: 3","Unnamed: 2"],axis=1,inplace=True)

# Estandarizamos los nombres de las columnas
hab_mex.rename(columns={"Estado" : "place", "Población (2020)" : "population"},inplace=True)

# Reordenamos
hab_mex = hab_mex[["idCountry","place","population"]]

# Obervamos
hab_mex.head()

   idCountry             place  population
0          3  Ciudad de México   9,209,944
1          3  Estado de México  17,511,369
2          3           Jalisco   8,348,151
3          3          Veracruz   8,062,703
4          3            Puebla   6,583,278

In [ ]:
# Exportamos a formato json
hab_mex.to_json("population_méxico(2020).json")

In [ ]:
# Aclaración para el uso de los datasets
""""Fecha y hora local en tiempo del centro de Mexico. Coordenadas geograficas (latitud y longitud) del epicentro en grados decimales. Profundidad en kilometros."
"La localizacion es solo una referencia a una localidad importante en cuanto a numero de habitantes y cercana al epicentro."
"Los registros con estatus verificado son los calculados y publicados de manera oportuna por al menos un analista de sismogramas."
"Los registros obtienen estatus revisado cuando se realiza un analisis, de ser posible, con mas y mejores datos para el calculo de parametros y cuyo tiempo de publicacion es variable."
"Esta informacion puede ser reproducida con fines no lucrativos siempre y cuando se mencione como fuente al Servicio Sismologico Nacional. De otra forma, requiere permiso previo por escrito de la institucion."
"Consulta nuestro Aviso Legal y Terminos de Uso en: www.ssn.unam.mx/aviso-legal"""